sudo: required

language: node_js
node_js:
  - "stable"

services:
  - docker

before_install:
  - docker build -t $DOCKER_USER/docker-node-api .

script:
  - docker run --name docker-node-api -d $DOCKER_USER/docker-node-api
  - docker ps | grep -q $DOCKER_USER/docker-node-api

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag $DOCKER_USER/docker-node-api $DOCKER_USER/docker-node-api:1.1.0
  - docker push $DOCKER_USER/docker-node-api:1.1.0
  - docker tag $DOCKER_USER/docker-node-api $DOCKER_USER/docker-node-api:latest
  - docker push $DOCKER_USER/docker-node-api:latest
