sudo: required

language: node_js
node_js:
  - "stable"

services:
  - docker

before_install:
  - dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
  - dnf install gh -y
  - docker build -t $DOCKER_USER/docker-node-api .

script:
  - docker run --name docker-node-api -d $DOCKER_USER/docker-node-api
  - docker ps | grep -q $DOCKER_USER/docker-node-api

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag $DOCKER_USER/docker-node-api $DOCKER_USER/docker-node-api:1.0.$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/docker-node-api:1.0.$TRAVIS_BUILD_NUMBER
  - docker tag $DOCKER_USER/docker-node-api $DOCKER_USER/docker-node-api:latest
  - docker push $DOCKER_USER/docker-node-api:latest
  - gh auth login --with-token <<< $GITHUB_ACCESS_TOKEN
  - gh release create 1.0.$TRAVIS_BUILD_NUMBER < <(echo 1.0.$TRAVIS_BUILD_NUMBER)
  - gh auth logout --hostname github.com < <(echo "y")
